macos_option_as_alt left

# Cmd+Backspace as "delete word back"
map cmd+backspace send_text all \x17

# ignore macos defaults
map alt+left   discard_event
map alt+right  discard_event
map cmd+left   discard_event
map cmd+right  discard_event

map alt+backspace  discard_event
map cmd+backspace  discard_event
